InterledgerProtocolHeader
DEFINITIONS
AUTOMATIC TAGS ::=
BEGIN

IMPORTS
	Timestamp,
	Address,
	Amount
	FROM InterledgerTypes
	
	Condition
	FROM CryptoConditions
	
	GenericHeaderPreamble
	FROM GenericExtensionHeaderFormat
;

InterledgerProtocolHeader ::= SEQUENCE {
	-- Destination ILP Address
	address Address,
	-- Amount which must be received at the destination
	amount Amount,
	-- Optional execution condition and expiry date
	conditional SEQUENCE {
		-- Condition of the transfer
		condition Condition,
		-- Expiry date of the transfer
		expiresAt Timestamp
	} OPTIONAL
}

END
